mutation CreateInstitutionRequest($input: CreateInstitutionRequestInput!) {
  createInstitutionRequest(input: $input) {
    message
    data {
      id
    }
  }
}

query GetInstitutionRequestById($id: Int!) {
  institutionRequest(id: $id) {
    id
    institutionName
  }
}

query GetInstitutionRequests($query: QueryParams) {
  institutionRequests(query: $query) {
    items {
      id
      institutionName
      adminEmail
      slug
      status
      progressData {
        institutionInfo {
          name
          logoFileUpload {
            id
          }
        }
        adminInfos {
          lastName
          firstName
          email
        }
      }
    }
    meta {
      totalItems
    }
  }
}

mutation DeleteInstitutionRequestById($id: Int!) {
  deleteInstitutionRequest(id: $id) {
    message
  }
}

mutation UpdateInstitutionRequest(
  $id: Int!
  $params: UpdateInstitutionRequestInput!
) {
  updateInstitutionRequest(id: $id, params: $params) {
    message
    data {
      id
    }
  }
}

mutation RegisterInstitutionRequest($input: RegisterInstitutionRequestInput!) {
  registerInstitutionRequest(input: $input) {
    message
    data {
      id
    }
  }
}

mutation UpdateInstitutionRequestProgress(
  $id: Int!
  $params: InstitutionRequestProgressDataInput!
) {
  updateInstitutionRequestProgress(id: $id, params: $params) {
    message
  }
}

mutation CompleteInstitutionRequest(
  $id: String!
) {
  completeRequestRegistration(input: {id: $id}) {
    message
  }
}
